### ISSUE TITLE
Registro de exámenes médicos

### ISSUE THREAD

**Issue by JonathanRojas** [JonathanRojas/Kaplan#14]
Funcionalidad para el registro de exámenes médicos, la cual permite subir archivos multimedia tales como imágenes y/o documentos, en formato jpg, pdf, doc, xls, los cuales se asocian a un paciente en particular, de este modo sus exámenes están disponible en todo momento para consultar.

**Comment by candia-666** [comment]
realizado con commits c248338bfd9c9f73b7d41bb50d15b303ff565420
